[package]
name = "iota-kerladdress-wasm"
version = "0.1.0"
authors = ["Thoralf-M"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.62"
iota-signing = "0.2.1"
iota-conversion = "0.3.0"